### ISSUE TITLE
Terminal latency - st

### ISSUE THREAD

**Issue by avih** [madnight/blog#25]
Hi, and good post about the terminal latency.

Regarding st, however, you should know that the latency is configurable, and by default it's adaptive between 8ms and 32ms.

Generally speaking, there's a tradeoff between latency and throughput/flicker.

The smaller the latency, the worse the throughput is (e.g. in `cat huge.txt`) because the terminal has to render more frequently, and the more flicker-prone it becomes, for instance when the terminal updates the screen before the application completed its "output batch" - which then requires another screen update once the output batch is complete, e.g. when holding page-down in auto-repeat in `vim` or `less`.

This behavior is not unique to `st`, but what is unique to st is that it's configurable, and can be adaptive.

By default it's adaptive between 8 and 32 ms, and tries to draw as soon as possible after the application-output batch completes, i.e. the terminal input becomes idle.

To disable the latency completely. i.e. draw as soon as the terminal reads anything from the app/KB, set `minlatency = 0` (at `config.h`), and keep `maxlatency` non-zero. This would remove any latency in st itself, though there may still be some latency elsewhere - outside the control of `st`.

To set a fixed, non-zero, latency, set minlatency and maxlatency to the same value (in ms).

To set adaptive latrency, set the range via minlatency and maxlatency, which is in practice typically results in latency closer to minlatency, but can be longer - up to maxlatency, if the application output is slow. The default of 8..32 is on the conservative side, and one could instead use 4..16 or 2..4 or any other range they prefer.

Just FYI, and it would be nice if you could update your tables, maybe by adding a mimimum latency test (minlatency=0), and/or low-latency config, e.g. minlatency=2, maxlatency=4, or maybe 2..8, etc.

**Comment by avih** [comment]
Also, as of few hours ago, the default was changed to `minlatency = 2` :)

**Comment by madnight** [comment]
Hi @avih, thanks for your valuable feedback. Are you one of the authors of st?

`minlatency = 2` seems like a sensible default, at least from my latency sensitive perspective.

I will update my blog post to mention the new commit and the possibility of configuring the minlatency value through recompiling.

**Comment by avih** [comment]
> Are you one of the authors of st?

I contributed some code to st over the years, including the configurable and adaptive latency code.

> I will update my blog post to mention the new commit and the possibility of configuring the minlatency value through recompiling.

Nice. Mind posting a comment here once you do?

Thanks in advance.

**Comment by madnight** [comment]
@avih here we go https://github.com/madnight/blog/commit/d18199b958a75d3758b384e52ae9cc44317e5155

**Comment by avih** [comment]
Looks good. Thanks!
